# Generated by Django 5.2.1 on 2025-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='type',
            new_name='promotion_type',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
