# Generated by Django 5.2.1 on 2025-09-18 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='book',
            name='promotions',
            field=models.ManyToManyField(related_name='books', through='shop.PromoBook', through_fields=('book', 'promotion'), to='shop.promotion'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='shop.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='shop.genre', verbose_name='Жанр'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'book')},
        ),
    ]
