# Generated by Django 5.2.1 on 2025-09-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_discount_book_promotions_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/files/', verbose_name='Файл книги (PDF)'),
        ),
    ]
