# Generated by Django 5.2.1 on 2025-09-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)'),
        ),
    ]
